

const TESTDATA = Dict("number_of_females_1"=> 2,
             "number_of_females_2"=> 3,
             "number_of_females_3"=> 3,
             "number_of_males_1"=> 11,
             "number_of_males_2"=> 13,
             "number_of_males_3"=> 42,
             "number_of_initial_vacancies_1"=> 0,
             "number_of_initial_vacancies_2"=> 0,
             "number_of_initial_vacancies_3"=> 0,
             "hiring_rate_women_1"=> 0.2059,
             "hiring_rate_women_2"=> 0.0588,
             "hiring_rate_women_3"=> 0.00,
             "hiring_rate_men_1"=> 0.5294,
             "hiring_rate_men_2"=> 0.1176,
             "hiring_rate_men_3"=> 0.0882,
             "attrition_rate_women_1"=> 0.0615,
             "attrition_rate_women_2"=> 0.00,
             "attrition_rate_women_3"=> 0.06,
             "attrition_rate_men_1"=> 0.0859,
             "attrition_rate_men_2"=> 0.0473,
             "attrition_rate_men_3"=> 0.0414,
             "female_promotion_probability_1"=> 0.0769,
             "female_promotion_probability_2"=> 0.1111,
             "male_promotion_probability_1"=> 0.0707,
             "male_promotion_probability_2"=> 0.0946,
             "t_fpct"=> 0.15,
             "upperbound"=> 94,
             "lowerbound"=> 74,
             "duration"=> 20,
             "annotation_text"=> "this is an annotation",
             "growth_rate"=> [0.00],
             "model_name" => "model 3 with drift")
